### ISSUE TITLE
Add more plugin

### ISSUE THREAD

**Issue by MikaXII** [digitalLumberjack/docker-nodebb#1]
Bon je la fait frenchi,

https://github.com/digitalLumberjack/docker-nodebb/blob/master/Dockerfile#L41

Je vois que tu ajoutes un package donc la question : 
1 - On fait une image de base et on ajoute nos plugins après install ?
2 - Osef on install nos packages direct car après tout c'est pour nous ?

**Comment by digitalLumberjack** [comment]
Nope je vais faire un script qui installe des plugins automatiquement.
Il faut vraiment que l'image, au pop, soit prete a recevoir les requetes, et donc qu'elle soit dans son etat final :)

**Comment by digitalLumberjack** [comment]
https://github.com/digitalLumberjack/docker-nodebb/commit/3caeda6a196e9090ff588038bbaef7aede5e29bb
